### ISSUE TITLE
requirements.txt bug

### ISSUE THREAD

**Issue by aiamadeus** [LGiki/JMUClassScheduleToiCalender#1]
当我运行pip3 install -r requirements.txt时出现这个错误：Could not find a version that satisfies the requirement icalendar==4.0.3.dev0。
把requirements.txt里的icalendar==4.0.3.dev0改成icalendar==4.0.3就可以了。

**Comment by aiamadeus** [comment]
当我运行python3 jmu_class_schedule_to_ics.py时，报错：
Traceback (most recent call last):
  File "jmu_class_schedule_to_ics.py", line 2, in <module>
    from icalendar import Calendar, Event
ModuleNotFoundError: No module named 'icalendar'

**Comment by LGiki** [comment]
感谢提醒，icalendar 确实已经更新到了 4.0.3 这个版本了，原来的 4.0.3.dev0 在 PyPI 中已经不存在。已经修改相应的 requirements.txt。

至于你说的第二个问题，ModuleNotFoundError：未找到相应的模块。我刚刚在一台未安装 icalendar 包的机器上用 pip3 install -r requirements.txt 安装之后运行了一下是没有问题的。你可以排查一下是不是 icalendar 这个 Python 模块安装出错了，可以在 python 环境下执行 `import icalendar` 看看是否会报错。
